### ISSUE TITLE
spectra display

### ISSUE THREAD

**Issue by mhagdorn** [TeamPiccolo/piccolo3-web#1]
When the display tab is opened both upwelling and downwelling spectra are shown. Add option to selector to show both upwelling and downwelling spectra.

**Comment by mhagdorn** [comment]
add selector to show both is tricky, so instead it is now showing the selected data on opening the page

**Comment by amacarth** [comment]
Could it no default as it now does and have an All label the up and down being the dropdown options?  But if it's a hassle leave as easiest for you

**Comment by mhagdorn** [comment]
it certainly needs more thinking. I figured this is a quick win and doesn't surprise users. I would like to change the display at some stage but that has to wait.

**Comment by amacarth** [comment]
OK quick win is good
